
set_start_date:
  name: Set start date
  description: Set the start/replace date for a consumable entity (YYYY-MM-DD)
  fields:
    entity_id:
      description: Sensor entity to update
      example: sensor.water_filter_days_remaining
      selector:
        entity:
          domain: sensor
    start_date:
      description: Start date (YYYY-MM-DD)
      example: "2025-01-01"
      selector:
        date: {}

set_duration:
  name: Set duration (days)
  description: Update the duration in days for a consumable entity
  fields:
    entity_id:
      description: Sensor entity to update
      selector:
        entity:
          domain: sensor
    duration_days:
      description: Duration in days (>=1)
      example: 90
      selector:
        number:
          min: 1
          max: 1825
          mode: box

mark_replaced:
  name: Mark replaced today
  description: Sets the start date to today
  fields:
    entity_id:
      description: Sensor entity to update
      selector:
        entity:
          domain: sensor

set_expiry_date:
  name: Set expiry date
  description: Set the expiry/due date for a consumable entity (YYYY-MM-DD)
  fields:
    entity_id:
      description: Sensor entity to update
      selector:
        entity:
          domain: sensor
    expiry_date:
      description: Expiry date (YYYY-MM-DD)
      example: "2025-02-01"
      selector:
        date: {}
